/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../src/app/components/main.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../src/app/components/secondchart.component';
import * as import9 from './secondchart.component.ngfactory';
import * as import10 from '../../../../src/app/components/firstchart.component';
import * as import11 from './firstchart.component.ngfactory';
export class Wrapper_MainComponent {
  /*private*/ _eventHandler:Function;
  context:import0.MainComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.MainComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_MainComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_MainComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.MainComponent>;
  _MainComponent_0_3:Wrapper_MainComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MainComponent_Host0,renderType_MainComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app-root',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_MainComponent0(this.viewUtils,this,0,this._el_0);
    this._MainComponent_0_3 = new Wrapper_MainComponent();
    this.compView_0.create(this._MainComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._MainComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MainComponent) && (0 === requestNodeIndex))) { return this._MainComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MainComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const MainComponentNgFactory:import7.ComponentFactory<import0.MainComponent> = new import7.ComponentFactory<import0.MainComponent>('app-root',View_MainComponent_Host0,import0.MainComponent);
const styles_MainComponent:any[] = ([] as any[]);
var renderType_MainComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_MainComponent,{});
export class View_MainComponent0 extends import1.AppView<import0.MainComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  compView_28:import1.AppView<import8.SecondChartComponent>;
  _SecondChartComponent_28_3:import9.Wrapper_SecondChartComponent;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _el_52:any;
  _el_53:any;
  _text_54:any;
  _el_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _el_64:any;
  compView_64:import1.AppView<import10.FirstChartComponent>;
  _FirstChartComponent_64_3:import11.Wrapper_FirstChartComponent;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MainComponent0,renderType_MainComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n        ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray4(4,'class','container chart','id','chart2'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n                \n                ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-12 col-md-4 col-lg-4'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n                    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n                      ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'Comparison of mean ratings between age-ranges during the years.',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_7,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_7,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_13 = this.renderer.createText(this._el_7,'\n                      X-Axis : Years ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_7,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_7,'\n                      Y-Axis : Ratings ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_7,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_7,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_18 = this.renderer.createText(this._el_7,'\n                      In this chart every line represents an age range, and it tells you how the mean of the ratings have changed over the years. This, on people of a specified gender. ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_7,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_7,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_21 = this.renderer.createText(this._el_7,'\n                      - Youngsters are always foolish and happy.\n                    ',(null as any));
    this._text_22 = this.renderer.createText(this._el_5,'\n                ',(null as any));
    this._text_23 = this.renderer.createText(this._el_3,'\n\n                ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_3,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-12 col-md-8 col-lg-8'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n                    ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_24,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n                      ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_26,'secondchart',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_28 = new import9.View_SecondChartComponent0(this.viewUtils,this,28,this._el_28);
    this._SecondChartComponent_28_3 = new import9.Wrapper_SecondChartComponent();
    this.compView_28.create(this._SecondChartComponent_28_3.context);
    this._text_29 = this.renderer.createText(this._el_26,'\n                    ',(null as any));
    this._text_30 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._text_31 = this.renderer.createText(this._el_3,'\n                \n            ',(null as any));
    this._text_32 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._text_33 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,parentRenderNode,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_35 = this.renderer.createText(parentRenderNode,'\n        ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray4(4,'class','container chart','id','chart1'),(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'\n            ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_36,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'\n                \n                ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_38,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-12 col-md-4 col-lg-4'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'\n                    ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_40,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'\n                    ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_42,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'For each rating, comparison between the years of the rating-percentage.',(null as any));
    this._text_46 = this.renderer.createText(this._el_42,'\n                    ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_42,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_42,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_49 = this.renderer.createText(this._el_42,'\n                      X-Axis : Ratings ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_42,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_51 = this.renderer.createText(this._el_42,'\n                      Y-Axis : % ',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_42,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_42,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_54 = this.renderer.createText(this._el_42,'\n                      \n                      With this chart you can see how satisfied of their lives were the people of a certain gender, in a certain age range across the years 2010-2016. ',(null as any));
    this._el_55 = import3.createRenderElement(this.renderer,this._el_42,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_42,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_57 = this.renderer.createText(this._el_42,'\n                      - Pizza kept the gaussian on the right side.\n                    ',(null as any));
    this._text_58 = this.renderer.createText(this._el_40,'\n                ',(null as any));
    this._text_59 = this.renderer.createText(this._el_38,'\n\n                ',(null as any));
    this._el_60 = import3.createRenderElement(this.renderer,this._el_38,'div',new import3.InlineArray2(2,'class','col-xs-12 col-sm-12 col-md-8 col-lg-8'),(null as any));
    this._text_61 = this.renderer.createText(this._el_60,'\n                    ',(null as any));
    this._el_62 = import3.createRenderElement(this.renderer,this._el_60,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_63 = this.renderer.createText(this._el_62,'\n                      ',(null as any));
    this._el_64 = import3.createRenderElement(this.renderer,this._el_62,'firstchart',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_64 = new import11.View_FirstChartComponent0(this.viewUtils,this,64,this._el_64);
    this._FirstChartComponent_64_3 = new import11.Wrapper_FirstChartComponent();
    this.compView_64.create(this._FirstChartComponent_64_3.context);
    this._text_65 = this.renderer.createText(this._el_62,'\n                    ',(null as any));
    this._text_66 = this.renderer.createText(this._el_60,'\n                ',(null as any));
    this._text_67 = this.renderer.createText(this._el_38,'\n\n            ',(null as any));
    this._text_68 = this.renderer.createText(this._el_36,'\n        ',(null as any));
    this._text_69 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import8.SecondChartComponent) && (28 === requestNodeIndex))) { return this._SecondChartComponent_28_3.context; }
    if (((token === import10.FirstChartComponent) && (64 === requestNodeIndex))) { return this._FirstChartComponent_64_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SecondChartComponent_28_3.ngDoCheck(this,this._el_28,throwOnChange);
    this._FirstChartComponent_64_3.ngDoCheck(this,this._el_64,throwOnChange);
    this.compView_28.internalDetectChanges(throwOnChange);
    this.compView_64.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_28.destroy();
    this.compView_64.destroy();
  }
}