/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../src/app/components/secondchart.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import9 from '../../../node_modules/@angular/forms/src/directives/radio_control_value_accessor.ngfactory';
import * as import10 from '../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import11 from '../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import12 from '@angular/core/src/linker/view_container';
import * as import13 from '@angular/core/src/change_detection/change_detection_util';
import * as import14 from '@angular/core/src/linker/element_ref';
import * as import15 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import16 from '@angular/forms/src/directives/default_value_accessor';
import * as import17 from '@angular/forms/src/directives/control_value_accessor';
import * as import18 from '@angular/forms/src/directives/ng_model';
import * as import19 from '@angular/forms/src/directives/ng_control';
import * as import20 from '@angular/forms/src/directives/ng_control_status';
import * as import21 from '../../../node_modules/ng2-charts/charts/charts.ngfactory';
import * as import22 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import23 from '@angular/core/src/linker/template_ref';
import * as import24 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import25 from 'ng2-charts/charts/charts';
import * as import26 from '@angular/common/src/directives/ng_for';
export class Wrapper_SecondChartComponent {
  /*private*/ _eventHandler:Function;
  context:import0.SecondChartComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.SecondChartComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_SecondChartComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_SecondChartComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.SecondChartComponent>;
  _SecondChartComponent_0_3:Wrapper_SecondChartComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SecondChartComponent_Host0,renderType_SecondChartComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'secondchart',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_SecondChartComponent0(this.viewUtils,this,0,this._el_0);
    this._SecondChartComponent_0_3 = new Wrapper_SecondChartComponent();
    this.compView_0.create(this._SecondChartComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._SecondChartComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SecondChartComponent) && (0 === requestNodeIndex))) { return this._SecondChartComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SecondChartComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const SecondChartComponentNgFactory:import7.ComponentFactory<import0.SecondChartComponent> = new import7.ComponentFactory<import0.SecondChartComponent>('secondchart',View_SecondChartComponent_Host0,import0.SecondChartComponent);
const styles_SecondChartComponent:any[] = ([] as any[]);
class View_SecondChartComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _DefaultValueAccessor_2_3:import8.Wrapper_DefaultValueAccessor;
  _RadioControlValueAccessor_2_4:import9.Wrapper_RadioControlValueAccessor;
  _NG_VALUE_ACCESSOR_2_5:any[];
  _NgModel_2_6:import10.Wrapper_NgModel;
  _NgControl_2_7:any;
  _NgControlStatus_2_8:import11.Wrapper_NgControlStatus;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  /*private*/ _expr_12:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_SecondChartComponent1,renderType_SecondChartComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_12 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','options'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n       ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'input',new import3.InlineArray8(6,'class','opt','name','gender_2','type','radio'),(null as any));
    this._DefaultValueAccessor_2_3 = new import8.Wrapper_DefaultValueAccessor(this.renderer,new import14.ElementRef(this._el_2));
    this._RadioControlValueAccessor_2_4 = new import9.Wrapper_RadioControlValueAccessor(this.renderer,new import14.ElementRef(this._el_2),this.parentView.parentView.injectorGet(import15.RadioControlRegistry,this.parentView.parentIndex),this.injector(2));
    this._NG_VALUE_ACCESSOR_2_5 = [
      this._DefaultValueAccessor_2_3.context,
      this._RadioControlValueAccessor_2_4.context
    ]
    ;
    this._NgModel_2_6 = new import10.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_2_5);
    this._NgControl_2_7 = this._NgModel_2_6.context;
    this._NgControlStatus_2_8 = new import11.Wrapper_NgControlStatus(this._NgControl_2_7);
    this._text_3 = this.renderer.createText(this._el_0,'',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_0,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray8(8,'ngModelChange',(null as any),'change',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_2));
    this._NgModel_2_6.subscribe(this,this.eventHandler(this.handleEvent_2),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.DefaultValueAccessor) && (2 === requestNodeIndex))) { return this._DefaultValueAccessor_2_3.context; }
    if (((token === import15.RadioControlValueAccessor) && (2 === requestNodeIndex))) { return this._RadioControlValueAccessor_2_4.context; }
    if (((token === import17.NG_VALUE_ACCESSOR) && (2 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_2_5; }
    if (((token === import18.NgModel) && (2 === requestNodeIndex))) { return this._NgModel_2_6.context; }
    if (((token === import19.NgControl) && (2 === requestNodeIndex))) { return this._NgControl_2_7; }
    if (((token === import20.NgControlStatus) && (2 === requestNodeIndex))) { return this._NgControlStatus_2_8.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DefaultValueAccessor_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_2_1_0:any = 'gender_2';
    this._RadioControlValueAccessor_2_4.check_name(currVal_2_1_0,throwOnChange,false);
    const currVal_2_1_1:any = import3.inlineInterpolate(1,'',this.context.$implicit,'');
    this._RadioControlValueAccessor_2_4.check_value(currVal_2_1_1,throwOnChange,false);
    this._RadioControlValueAccessor_2_4.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_2_2_0:any = 'gender_2';
    this._NgModel_2_6.check_name(currVal_2_2_0,throwOnChange,false);
    const currVal_2_2_1:any = this.parentView.context.curr_gender;
    this._NgModel_2_6.check_model(currVal_2_2_1,throwOnChange,false);
    this._NgModel_2_6.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgControlStatus_2_8.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgControlStatus_2_8.checkHost(this,this,this._el_2,throwOnChange);
    const currVal_12:any = import3.inlineInterpolate(1,' ',this.context.$implicit,'');
    if (import3.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setText(this._text_3,currVal_12);
      this._expr_12 = currVal_12;
    }
  }
  destroyInternal():void {
    this._RadioControlValueAccessor_2_4.ngOnDestroy();
    this._NgModel_2_6.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_2_3.handleEvent(eventName,$event) && result);
    result = (this._RadioControlValueAccessor_2_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.curr_gender = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'change')) {
      const pd_sub_1:any = ((<any>this.parentView.context.toggleGender(this.context.$implicit)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
}
class View_SecondChartComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_SecondChartComponent2,renderType_SecondChartComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_6 = import13.UNINITIALIZED;
    this._expr_7 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','options'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n       ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'input',new import3.InlineArray8(8,'checked','','class','opt','name','age_selection','type','checkbox'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_0,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'change',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_6:any = import3.inlineInterpolate(1,'',this.context.$implicit,'');
    if (import3.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementProperty(this._el_2,'value',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = import3.inlineInterpolate(1,' ',this.context.$implicit,'');
    if (import3.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_3,currVal_7);
      this._expr_7 = currVal_7;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'change')) {
      const pd_sub_0:any = ((<any>this.parentView.context.toggleAge(this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_SecondChartComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_SecondChartComponent,{});
export class View_SecondChartComponent0 extends import1.AppView<import0.SecondChartComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _BaseChartDirective_3_3:import21.Wrapper_BaseChartDirective;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _vc_8:import12.ViewContainer;
  _TemplateRef_8_5:any;
  _NgFor_8_6:import22.Wrapper_NgFor;
  _el_9:any;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _vc_11:import12.ViewContainer;
  _TemplateRef_11_5:any;
  _NgFor_11_6:import22.Wrapper_NgFor;
  _text_12:any;
  _text_13:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SecondChartComponent0,renderType_SecondChartComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'style','display: block; '),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'canvas',new import3.InlineArray2(2,'baseChart',''),(null as any));
    this._BaseChartDirective_3_3 = new import21.Wrapper_BaseChartDirective(new import14.ElementRef(this._el_3));
    this._text_4 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._text_5 = this.renderer.createText(parentRenderNode,'\n\n    ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'style','display: block; max-width: 50vw;'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._vc_8 = new import12.ViewContainer(8,6,this,this._anchor_8);
    this._TemplateRef_8_5 = new import23.TemplateRef_(this,8,this._anchor_8);
    this._NgFor_8_6 = new import22.Wrapper_NgFor(this._vc_8.vcRef,this._TemplateRef_8_5,this.parentView.injectorGet(import24.IterableDiffers,this.parentIndex),this.ref);
    this._el_9 = import3.createRenderElement(this.renderer,this._el_6,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n      \n      ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._vc_11 = new import12.ViewContainer(11,6,this,this._anchor_11);
    this._TemplateRef_11_5 = new import23.TemplateRef_(this,11,this._anchor_11);
    this._NgFor_11_6 = new import22.Wrapper_NgFor(this._vc_11.vcRef,this._TemplateRef_11_5,this.parentView.injectorGet(import24.IterableDiffers,this.parentIndex),this.ref);
    this._text_12 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._anchor_8,
      this._el_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._text_13
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.BaseChartDirective) && (3 === requestNodeIndex))) { return this._BaseChartDirective_3_3.context; }
    if (((token === import23.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import26.NgFor) && (8 === requestNodeIndex))) { return this._NgFor_8_6.context; }
    if (((token === import23.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import26.NgFor) && (11 === requestNodeIndex))) { return this._NgFor_11_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3_0_0:any = this.context.lineChartData;
    this._BaseChartDirective_3_3.check_datasets(currVal_3_0_0,throwOnChange,false);
    const currVal_3_0_1:any = this.context.lineChartLabels;
    this._BaseChartDirective_3_3.check_labels(currVal_3_0_1,throwOnChange,false);
    const currVal_3_0_2:any = this.context.lineChartOptions;
    this._BaseChartDirective_3_3.check_options(currVal_3_0_2,throwOnChange,false);
    const currVal_3_0_3:any = this.context.lineChartType;
    this._BaseChartDirective_3_3.check_chartType(currVal_3_0_3,throwOnChange,false);
    const currVal_3_0_4:any = this.context.lineChartColors;
    this._BaseChartDirective_3_3.check_colors(currVal_3_0_4,throwOnChange,false);
    const currVal_3_0_5:any = this.context.lineChartLegend;
    this._BaseChartDirective_3_3.check_legend(currVal_3_0_5,throwOnChange,false);
    this._BaseChartDirective_3_3.ngDoCheck(this,this._el_3,throwOnChange);
    const currVal_8_0_0:any = this.context.genders;
    this._NgFor_8_6.check_ngForOf(currVal_8_0_0,throwOnChange,false);
    this._NgFor_8_6.ngDoCheck(this,this._anchor_8,throwOnChange);
    const currVal_11_0_0:any = this.context.ages;
    this._NgFor_11_6.check_ngForOf(currVal_11_0_0,throwOnChange,false);
    this._NgFor_11_6.ngDoCheck(this,this._anchor_11,throwOnChange);
    this._vc_8.detectChangesInNestedViews(throwOnChange);
    this._vc_11.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_8.destroyNestedViews();
    this._vc_11.destroyNestedViews();
    this._BaseChartDirective_3_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 8)) { return new View_SecondChartComponent1(this.viewUtils,this,8,this._anchor_8,this._vc_8); }
    if ((nodeIndex == 11)) { return new View_SecondChartComponent2(this.viewUtils,this,11,this._anchor_11,this._vc_11); }
    return (null as any);
  }
}